---
title: "RStudio Workshop 2025"
format: html
---

## Peningkatan Research Quality dengan RStudio

Situs ini berfungsi sebagai repositori untuk slide dan kode (sintaks) untuk peserta workshop RStudio, di Universitas Jambi, 6 Mei 2025.

**Speaker**: Prof. Dr. Muhammad Firdaus (Pengurus Pusat ISEI Bidang V & Atdikbud KBRI Kuala Lumpur)

**Instructor**: Deri Siswara (IPB University)

## Schedule

*Slide dan sintaks akan tersedia secara bertahap di bawah ini.*

::::: table-schedule
| Session | Material | Quiz |
|----------------------|---------------------------|----------------------|
| Sesi 1 | [Menulis Artikel Jurnal](01-basics.html) | \- |
| Sesi 2 | [Ekonometrika di RStudio](02-numpy.html) | [Quiz 1](https://forms.gle/AEXQi2hScPRTPtFh8){target="_blank"} |
| Sesi 3 | [Metode Kuantitatif di RStudio](03-pandas.html) | [Quiz 2](https://forms.gle/JSNcorbKADQmkg4Z8) |

```{=html}
<style type="text/css">
    .table-schedule table thead tr {width: 100%;}
    .table-schedule table thead tr th:nth-child(1) { width: 22%; }
    .table-schedule table thead tr th:nth-child(2) { width: 23%; }
    .table-schedule table thead tr th:nth-child(3) { width: 30%; }
    .table-schedule table thead tr th:nth-child(4) { width: 20%; }
</style>
```
:::::

::: {.callout-note appearance="simple"}
**Important - Jangan lupa membawa laptop Anda!**

Di workshop ini, bawa laptop yang sudah terinstal RStudio. Pastikan Anda sudah menginstal R dan RStudio di laptop Anda sebelum workshop dimulai. Cara menginstal R dan RStudio dapat ditemukan di **Pre-workshop activities**
:::

## Pre-workshop activities

Workshop ini akan menggunakan RStudio, sebuah lingkungan pengembangan terintegrasi (IDE) gratis dan open-source untuk R.

**Silakan instal hal-hal berikut di laptop Anda sebelum workshop dimulai:**

1.  Unduh dan instal versi terbaru dari [R](https://cran.r-project.org/) sesuai dengan sistem operasi Anda.

    -   Jika Anda menggunakan Windows, selama instalasi, pastikan untuk memilih opsi untuk menambahkan R ke PATH sistem Anda.

2.  Unduh dan instal [RStudio](https://posit.co/download/rstudio-desktop/), IDE untuk R.

3.  Setelah Anda menginstal RStudio, buka dan pastikan bahwa RStudio mengenali instalasi R Anda. Anda dapat memeriksanya dengan pergi ke `Tools > Global Options > General` dan memverifikasi versi R.

4.  Kenali antarmuka RStudio dengan menjelajahi panel-panelnya (Console, Environment, Files, Plots, dll.).

5.  Isi [**survei pra-workshop**](https://smusg.asia.qualtrics.com/jfe/form/SV_1Nx06jl6oFCnNNY)! Harap selesaikan ini sebelum sesi 1 dimulai.

## Datasets

::: {.callout-note appearance="simple" title="What is a CSV?"}
A CSV (Comma-Separated Values) file is a type of file that stores data in a plain text format. Each line in the file represents a row of data, and within each row, individual pieces of data (like numbers or words) are separated by commas.

This format is commonly used for storing and transferring data, especially in spreadsheets and databases. Because it is literally just plain text, it is an ideal format if you have large amount of data.

You can open CSV files in Excel, Google Sheets, or even Notepad!
:::

### Dataset 1: sg-gdp.csv

For session 2 of this workshop, we will be using small dataset stored in a CSV file called `sg-gdp.csv`.

```{=html}
<a href="https://raw.githubusercontent.com/bellaratmelia/2024-python-macroecons/main/data/sg-gdp.csv" type="button" class="btn btn-success">Click here to open sg-gdp.csv, and then Ctrl + S / Cmd + S to save it locally into your data folder</a>
```

### Dataset 2: unemployment-age.csv

For session 3 of this workshop, we will be using small dataset stored in a CSV file called `unemployment-age.csv`. This is a time series data that tracks unemployment rate for various age groups in United States, retrieved from [Federal Reserve Economic Data (FRED)](https://fred.stlouisfed.org/).

```{=html}
<a href="https://raw.githubusercontent.com/bellaratmelia/2024-python-macroecons/main/data/unemployment-age.csv" type="button" class="btn btn-success">Click here to open unemployment-age.csv, and then Ctrl + S / Cmd + S to save it locally into your data folder</a>
```
